path.config: /usr/share/logstash/pipeline/logstash.conf
pipeline:
  batch:
    delay: 5
    size: 125
xpack.monitoring.elasticsearch.password: changeme
xpack.monitoring.elasticsearch.url: http://elasticsearch:9200
xpack.monitoring.elasticsearch.username: logstash_system
